# Generated by Django 4.1.10 on 2024-05-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0002_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maple.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, through='maple.CartProduct', to='maple.product'),
        ),
    ]
