# Generated by Django 4.1.10 on 2024-05-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0004_remove_cartproduct_cart_remove_cartproduct_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
