# Generated by Django 4.1.10 on 2024-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maple', '0005_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(default='', max_length=50, null=True)),
                ('subcategory', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(max_length=800, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='static/img')),
            ],
        ),
    ]
