# Generated by Django 4.1.10 on 2024-05-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
